#==========================================
#SERVER CONFIG
#==========================================

server.port=8080

#==========================================
#MONGODB CONFIG
#==========================================

spring.data.mongodb.host=localhost
spring.data.mongodb.host=27017
spring.data.mongodb.database=E-MART

#==========================================
#EMAIL CONFIG
#==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-emil@gmail.com
spring.mail.password=your-app-specific-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

#==========================================
#Razorpay CONFIG
#==========================================

razorpay.key.id=rzp_test_YOUR_KEY_ID
razorpay.key.secret=YOUR_KEY_SECRET

#==========================================
#JWT CONFIG
#==========================================

jwt.secret=YOUR_VERY_LONG_SECRET_KEY_FOR_JWT_SIGNING_MIN_256_BITS
jwt.expiration=86400000

#==========================================
# UPLOAD CONFIG
#==========================================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#==========================================
#APP CONFIG
#==========================================

spring.application.name=E-MART


server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param